services:
  - type: web
    name: ai-image-editor-server
    env: node
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src/.python-packages