services:
  - type: web
    name: ai-image-editor-server
    env: node
    buildCommand: pip install -r requirements.txt && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production