services:
  - type: web
    name: ai-image-editor-server
    env: node
    buildCommand: |
      npm install
      # Install Python dependencies using Node.js environment
      python3 -m pip install --user rembg pillow
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHON_PATH
        value: /opt/render/project/src/.local/bin